### ISSUE TITLE
Object.__proto__ should quote with "`"

### ISSUE THREAD

**Issue by yangg** [simongong/js-stackoverflow-highest-votes#6]
https://github.com/simongong/js-stackoverflow-highest-votes/blob/master/questions11-20/how-javascript-prototype-works.md

`Object.__proto__`

**Comment by simongong** [comment]
Nice catch! Thanks.

Fixed by https://github.com/simongong/js-stackoverflow-highest-votes/commit/3edc5a953866070dcc2ebddb0b51e74582ec92a3

Closing.
